### ISSUE TITLE
cat and > command not work!!

### ISSUE THREAD

**Issue by xiaojue** [jeremyfa/node-exec-sync#15]
run execSync("cat 1.js 2.js > 3.js"); command

3.js is empty ？ why？

or run like this command：

execSync('java -jar ' + this.jsTool + ' --js=' + jsfile + ' --js_output_file=' + target);

the target file is empty too。

but like these command:

exec("cat 1.js 2.js > 3.js");  
exec('java -jar ' + this.jsTool + ' --js=' + jsfile + ' --js_output_file=' + target);

it will be right....

**Comment by jeremyfa** [comment]
Quoting the repository README:

> IMPORTANT: This repository is no longer maintained.
>
>The same feature is now built-in with node v0.12: >https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options
