### ISSUE TITLE
Not compatible with nodeJS 5.1

### ISSUE THREAD

**Issue by luisamor** [jeremyfa/node-exec-sync#23]
Can you update the dependencies: "ffi": "=1.2.5" to the last version of ffi (2.0.0)? This is compatible with node 5.1.

https://github.com/nodejs/node-gyp/issues/821#event-473268511

Thanks.

**Comment by jeremyfa** [comment]
https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options
