### ISSUE TITLE
warn: "Utf8String" type is deprecated, use "CString" instead

### ISSUE THREAD

**Issue by springuper** [jeremyfa/node-exec-sync#7]
Whenever i use exec-sync module, '"Utf8String" type is deprecated, use "CString" instead' will print on the screen. please check it.

My OS info is "CentOS release 5.4 (Final)".

**Comment by jeremyfa** [comment]
Quoting the repository README:

> IMPORTANT: This repository is no longer maintained.
>
>The same feature is now built-in with node v0.12: >https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options
